SET SCHEMA %schemaName%;

INSERT INTO KADAI_SCHEMA_VERSION (ID, VERSION, CREATED)
VALUES (nextval('KADAI_SCHEMA_VERSION_ID_SEQ'), '12.0.0', CURRENT_TIMESTAMP);

-- "Indexes and simple table constraints involving the column will be automatically converted [...]."
-- See below Postgres-Docs:
-- https://www.postgresql.org/docs/17/sql-altertable.html#SQL-ALTERTABLE-DESC-SET-DATA-TYPE
ALTER TABLE CLASSIFICATION ALTER COLUMN APPLICATION_ENTRY_POINT TYPE VARCHAR(511);
ALTER TABLE CLASSIFICATION_HISTORY_EVENT ALTER COLUMN APPLICATION_ENTRY_POINT TYPE VARCHAR(511);

ALTER TABLE TASK ALTER COLUMN CUSTOM_1 TYPE VARCHAR(1023);
ALTER TABLE TASK ALTER COLUMN CUSTOM_2 TYPE VARCHAR(1023);
ALTER TABLE TASK ALTER COLUMN CUSTOM_3 TYPE VARCHAR(1023);
ALTER TABLE TASK ALTER COLUMN CUSTOM_4 TYPE VARCHAR(1023);
ALTER TABLE TASK ALTER COLUMN CUSTOM_5 TYPE VARCHAR(1023);
ALTER TABLE TASK ALTER COLUMN CUSTOM_6 TYPE VARCHAR(1023);
ALTER TABLE TASK ALTER COLUMN CUSTOM_7 TYPE VARCHAR(1023);
ALTER TABLE TASK ALTER COLUMN CUSTOM_8 TYPE VARCHAR(1023);
ALTER TABLE TASK ALTER COLUMN CUSTOM_9 TYPE VARCHAR(1023);
ALTER TABLE TASK ALTER COLUMN CUSTOM_10 TYPE VARCHAR(1023);
ALTER TABLE TASK ALTER COLUMN CUSTOM_11 TYPE VARCHAR(1023);
ALTER TABLE TASK ALTER COLUMN CUSTOM_12 TYPE VARCHAR(1023);
ALTER TABLE TASK ALTER COLUMN CUSTOM_13 TYPE VARCHAR(1023);
ALTER TABLE TASK ALTER COLUMN CUSTOM_14 TYPE VARCHAR(1023);
ALTER TABLE TASK ALTER COLUMN CUSTOM_15 TYPE VARCHAR(1023);
ALTER TABLE TASK ALTER COLUMN CUSTOM_16 TYPE VARCHAR(1023);
