SET search_path = %schemaName%;

CREATE INDEX IDX_TASK_COMPLETED_PARENT_BPI ON TASK
  (COMPLETED ASC, PARENT_BUSINESS_PROCESS_ID ASC, ID ASC);

CREATE INDEX IDX_TASK_PARENT_BPI_COMPLETED ON TASK
  (PARENT_BUSINESS_PROCESS_ID ASC, COMPLETED ASC, ID ASC);
