-- noinspection SqlNoDataSourceInspectionForFile

SET SCHEMA %schemaName%;

ALTER TABLE TASK ADD COLUMN IF NOT EXISTS IS_REOPENED BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE TASK SET IS_REOPENED=FALSE;

INSERT INTO KADAI_SCHEMA_VERSION (ID, VERSION, CREATED)
VALUES (nextval('KADAI_SCHEMA_VERSION_ID_SEQ'), '10.0.0', CURRENT_TIMESTAMP)
ON CONFLICT (VERSION) DO NOTHING;

CREATE INDEX IF NOT EXISTS IDX_TASK_WORKBASKET_ID ON TASK
    (WORKBASKET_ID ASC);
COMMIT WORK;

DO $$
    BEGIN
        ALTER TABLE WORKBASKET_HISTORY_EVENT RENAME COLUMN ORGLEVEL_1 TO ORG_LEVEL_1;
    EXCEPTION
        WHEN undefined_column THEN RAISE NOTICE 'Column ORGLEVEL_1 does not exist';
END $$;

DO $$
    BEGIN
        ALTER TABLE WORKBASKET_HISTORY_EVENT RENAME COLUMN ORGLEVEL_2 TO ORG_LEVEL_2;
    EXCEPTION
        WHEN undefined_column THEN RAISE NOTICE 'Column ORGLEVEL_2 does not exist';
END $$;

DO $$
    BEGIN
        ALTER TABLE WORKBASKET_HISTORY_EVENT RENAME COLUMN ORGLEVEL_3 TO ORG_LEVEL_3;
    EXCEPTION
        WHEN undefined_column THEN RAISE NOTICE 'Column ORGLEVEL_3 does not exist';
END $$;

DO $$
    BEGIN
        ALTER TABLE WORKBASKET_HISTORY_EVENT RENAME COLUMN ORGLEVEL_4 TO ORG_LEVEL_4;
    EXCEPTION
        WHEN undefined_column THEN RAISE NOTICE 'Column ORGLEVEL_4 does not exist';
END $$;

DO $$
    BEGIN
        ALTER TABLE USER_INFO RENAME COLUMN LASTNAME TO LAST_NAME;
    EXCEPTION
        WHEN undefined_column THEN RAISE NOTICE 'Column LAST_NAME does not exist';
END $$;