SET search_path = %schemaName%;

INSERT INTO KADAI_SCHEMA_VERSION (ID, VERSION, CREATED)
VALUES (nextval('KADAI_SCHEMA_VERSION_ID_SEQ'), '12.1.0', CURRENT_TIMESTAMP);

CREATE INDEX IDX_TASK_COMMENT_TASK_ID ON TASK_COMMENT
    (TASK_ID ASC);
