version: '3'
services:
  kadai-postgres_14:
    build: postgres_14
    ports:
      - "5102:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
  kadai-db2_11-5:
    image: taskana/db2:11.5
    environment:
      - LICENSE=accept
    ports:
      - "5101:50000"
