SET SCHEMA %schemaName%;

ALTER TABLE TASK_HISTORY_EVENT ADD COLUMN PROXY_ACCESS_ID VARCHAR(255) NULL;
ALTER TABLE WORKBASKET_HISTORY_EVENT ADD COLUMN PROXY_ACCESS_ID VARCHAR(255) NULL;
ALTER TABLE CLASSIFICATION_HISTORY_EVENT ADD COLUMN PROXY_ACCESS_ID VARCHAR(255) NULL;
