-- noinspection SqlNoDataSourceInspectionForFile

SET SCHEMA %schemaName%;

BEGIN
    DECLARE column_exists INT;
    SELECT COUNT(*) INTO column_exists
    FROM SYSCAT.COLUMNS
    WHERE TABSCHEMA = CURRENT SCHEMA
      AND TABNAME = 'TASK'
      AND COLNAME = 'IS_REOPENED';
    IF column_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TASK ADD COLUMN IS_REOPENED SMALLINT NOT NULL DEFAULT 0';
    END IF;
END;

UPDATE TASK SET IS_REOPENED=0;

BEGIN
    DECLARE version_exists INT;
    SELECT COUNT(*) INTO version_exists
    FROM KADAI_SCHEMA_VERSION
    WHERE VERSION = '10.0.0';
    IF version_exists = 0 THEN
        INSERT INTO KADAI_SCHEMA_VERSION (ID, VERSION, CREATED)
        VALUES (KADAI_SCHEMA_VERSION_ID_SEQ.NEXTVAL, '10.0.0', CURRENT_TIMESTAMP);
    END IF;
END;

BEGIN
    DECLARE index_exists INT;
    SELECT COUNT(*) INTO index_exists
    FROM SYSCAT.INDEXES
    WHERE INDNAME = 'IDX_TASK_WORKBASKET_ID'
      AND TABNAME = 'TASK';
    IF index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_TASK_WORKBASKET_ID ON TASK ("WORKBASKET_ID" ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS';
    END IF;
END;
COMMIT WORK;

BEGIN
    DECLARE column_exists INT;
    SELECT COUNT(*) INTO column_exists
    FROM SYSCAT.COLUMNS
    WHERE TABSCHEMA = CURRENT SCHEMA
      AND TABNAME = 'WORKBASKET_HISTORY_EVENT'
      AND COLNAME = 'ORGLEVEL_1';
    IF column_exists = 1 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE WORKBASKET_HISTORY_EVENT RENAME COLUMN ORGLEVEL_1 TO ORG_LEVEL_1';
    END IF;
END;

BEGIN
    DECLARE column_exists INT;
    SELECT COUNT(*) INTO column_exists
    FROM SYSCAT.COLUMNS
    WHERE TABSCHEMA = CURRENT SCHEMA
      AND TABNAME = 'WORKBASKET_HISTORY_EVENT'
      AND COLNAME = 'ORGLEVEL_2';
    IF column_exists = 1 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE WORKBASKET_HISTORY_EVENT RENAME COLUMN ORGLEVEL_2 TO ORG_LEVEL_2';
    END IF;
END;

BEGIN
    DECLARE column_exists INT;
    SELECT COUNT(*) INTO column_exists
    FROM SYSCAT.COLUMNS
    WHERE TABSCHEMA = CURRENT SCHEMA
      AND TABNAME = 'WORKBASKET_HISTORY_EVENT'
      AND COLNAME = 'ORGLEVEL_3';
    IF column_exists = 1 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE WORKBASKET_HISTORY_EVENT RENAME COLUMN ORGLEVEL_3 TO ORG_LEVEL_3';
    END IF;
END;

BEGIN
    DECLARE column_exists INT;
    SELECT COUNT(*) INTO column_exists
    FROM SYSCAT.COLUMNS
    WHERE TABSCHEMA = CURRENT SCHEMA
      AND TABNAME = 'WORKBASKET_HISTORY_EVENT'
      AND COLNAME = 'ORGLEVEL_4';
    IF column_exists = 1 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE WORKBASKET_HISTORY_EVENT RENAME COLUMN ORGLEVEL_4 TO ORG_LEVEL_4';
    END IF;
END;

BEGIN
    DECLARE column_exists INT;
    SELECT COUNT(*) INTO column_exists
    FROM SYSCAT.COLUMNS
    WHERE TABSCHEMA = CURRENT SCHEMA
      AND TABNAME = 'USER_INFO'
      AND COLNAME = 'LASTNAME';
    IF column_exists = 1 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE USER_INFO RENAME COLUMN LASTNAME TO LAST_NAME';
    END IF;
END;
