SET SCHEMA %schemaName%;

ALTER TABLE TASK ADD COLUMN IS_REOPENED SMALLINT NOT NULL DEFAULT 0;

UPDATE TASK SET IS_REOPENED=0;

INSERT INTO KADAI_SCHEMA_VERSION (ID, VERSION, CREATED)
VALUES (KADAI_SCHEMA_VERSION_ID_SEQ.NEXTVAL, '10.0.0', CURRENT_TIMESTAMP);

CREATE INDEX IDX_TASK_WORKBASKET_ID ON TASK
    ("WORKBASKET_ID" ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;
COMMIT WORK;

ALTER TABLE WORKBASKET_HISTORY_EVENT RENAME COLUMN ORGLEVEL_1 TO ORG_LEVEL_1;
ALTER TABLE WORKBASKET_HISTORY_EVENT RENAME COLUMN ORGLEVEL_2 TO ORG_LEVEL_2;
ALTER TABLE WORKBASKET_HISTORY_EVENT RENAME COLUMN ORGLEVEL_3 TO ORG_LEVEL_3;
ALTER TABLE WORKBASKET_HISTORY_EVENT RENAME COLUMN ORGLEVEL_4 TO ORG_LEVEL_4;

ALTER TABLE USER_INFO RENAME COLUMN LASTNAME TO LAST_NAME;