SET SCHEMA %schemaName%;

CREATE INDEX IDX_TASK_COMPLETED_PARENT_BPI ON TASK
    ("COMPLETED" ASC, "PARENT_BUSINESS_PROCESS_ID" ASC, "ID" ASC)
    ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;

CREATE INDEX IDX_TASK_PARENT_BPI_COMPLETED ON TASK
   ("PARENT_BUSINESS_PROCESS_ID" ASC, "COMPLETED" ASC, "ID" ASC)
   ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;
