SET SCHEMA %schemaName%;

INSERT INTO KADAI_SCHEMA_VERSION (ID, VERSION, CREATED)
VALUES (KADAI_SCHEMA_VERSION_ID_SEQ.NEXTVAL, '11.0.0', CURRENT_TIMESTAMP);

ALTER TABLE TASK_HISTORY_EVENT ADD COLUMN PROXY_ACCESS_ID VARCHAR(255) NULL;
ALTER TABLE WORKBASKET_HISTORY_EVENT ADD COLUMN PROXY_ACCESS_ID VARCHAR(255) NULL;
ALTER TABLE CLASSIFICATION_HISTORY_EVENT ADD COLUMN PROXY_ACCESS_ID VARCHAR(255) NULL;
